apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-down-hello-world
spec:
  schedule: "30 21 * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: scale-jobs-sa
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - kubectl scale deployment hello-world-node --replicas=3
          restartPolicy: OnFailure
