apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scale-jobs-role
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["hello-world-node"]
    verbs: ["get", "list", "update", "patch"]