apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scale-jobs-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: scale-jobs-sa
    namespace: default
roleRef:
  kind: Role
  name: scale-jobs-role
  apiGroup: rbac.authorization.k8s.io